# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: true
cache: packages

warnings_are_errors: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:opencpu/jq' # for EML
    packages:
      - librdf0-dev # for dataone
      - libv8-dev # for EML
      - libjq-dev # for EML
      - libudunits2-dev # for udunits2
