---
title: "trying_mn_loop"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



Lisa Eisner and Michael Lomas. Phytoplankton identifications in the northern Bering and Chukchi seas, quantified with FlowCAM image analysis, Arctic Integrated Ecosystem Research Program, August-September 2017. Research Workspace. 10.24431/rw1k5ac, version: 10.24431_rw1k5ac_20210709T212354Z.

```{r}

library(tidyverse)

#URl to package https://search.dataone.org/view/10.24431%2Frw1k5ac
path_folder <- "Data_test_phytoplankton"

# URL to download the dataset from DataONE
data_url <- "https://cn.dataone.org/cn/v2/resolve/8181dc0f-25fe-45c2-9bcd-0af54276aa62"

dir.create(path_folder, showWarnings = FALSE)

# Download the dataset and associated metdata 
data_folder <- SMALL_download_d1_data(data_url = data_url,path =  path_folder)




```

```{r}


library(tidyverse)
path_folder <- "Data_test_phytoplankton"

# URL to download the dataset from DataONE
data_url <- "https://cn.dataone.org/cn/v2/resolve/8181dc0f-25fe-45c2-9bcd-0af54276aa62"

dir.create(path_folder, showWarnings = FALSE)

# Download the dataset and associated metdata 
data_folder <- SMALL_download_d1_data(data_url = data_url,path =  path_folder)




```



```{r}

library(tidyverse)
path_folder <- "Data_test_eml"

# URL to download the dataset from DataONE
data_url <- "https://cn.dataone.org/cn/v2/resolve/https%3A%2F%2Fpasta.lternet.edu%2Fpackage%2Fdata%2Feml%2Fedi%2F853%2F1%2F1e02df107f9a4d5045bff3e4440ee202"

dir.create(path_folder, showWarnings = FALSE)

# Download the dataset and associated metdata 
data_folder <- SMALL_download_d1_data(data_url = data_url,path =  path_folder)

all_mns
```




```{r}

data_url <- "https://cn.dataone.org/cn/v2/resolve/4139539e-94e7-49cc-9c7a-5f879e438b16"
#this stuff is in the function already

  ## Try to get DataONE data_id from data_url ---------
  data_url <- utils::URLdecode(data_url)
  data_versions <- check_version(data_url, formatType = "data")

  if (nrow(data_versions) == 1) {
    data_id <- data_versions$identifier
  } else if (nrow(data_versions) > 1) {
    #get most recent version
    data_versions$dateUploaded <- lubridate::ymd_hms(data_versions$dateUploaded)
    data_id <- data_versions$identifier[data_versions$dateUploaded == max(data_versions$dateUploaded)]
  } else {
    stop("The DataONE ID could not be found for ", data_url)
  }
  
  data_nodes <- dataone::resolve(dataone::CNode("PROD"), data_id)
  d1c <- dataone::D1Client("PROD", data_nodes$data$nodeIdentifier[[1]])
  all_mns <- c(data_nodes$data$nodeIdentifier)
  cn <- dataone::CNode()
  
    ## Download Metadata ------------
  meta_id <- dataone::query(
    cn,
    list(q = sprintf('documents:"%s" AND formatType:"METADATA" AND -obsoletedBy:*', data_id),
         fl = "identifier")) %>%
    unlist()
  
  #This is the best version fo the loop so far. 
  if (length(all_mns) == 1) {
    mn <- dataone::getMNode(cn, all_mns)
     meta_obj <- dataone::getObject(mn, meta_id) 
  }  else {
    for (i in length(all_mns)){
      mn <- dataone::getMNode(cn, all_mns[i])
      stopifnot(!is.null(mn))
      meta_obj <- dataone::getObject(mn, meta_id) 
    }
  }



```

```{r}


metadata_tbl_KNB <- tibble(repo_name = "urn:node:KNB", metadata_type = c("eml://ecoinformatics.org/eml-2.1.1", "eml://ecoinformatics.org/eml-2.0.0", "eml://ecoinformatics.org/eml-2.0.1", "eml://ecoinformatics.org/eml-2.1.0", "https://eml.ecoinformatics.org/eml-2.2.0"), count = c(4409, 1981, 1337, 970, 608), already_supported_by_metajam = "Y")

metadata_tbl_EDI <- tibble(repo_name = "urn:node:EDI", metadata_type = c("eml://ecoinformatics.org/eml-2.1.1", "https://eml.ecoinformatics.org/eml-2.2.0", "eml://ecoinformatics.org/eml-2.1.0"), count = c(545, 381, 19), already_supported_by_metajam = "Y")


metadata_tbl_ARCTIC <- tibble(repo_name = "urn:node:ARCTIC", metadata_type = c("eml://ecoinformatics.org/eml-2.1.1", "http://www.isotc211.org/2005/gmd", "https://eml.ecoinformatics.org/eml-2.2.0", "https://purl.dataone.org/portals-1.0.0", "http://ns.dataone.org/metadata/schema/onedcx/v1.0", "eml://ecoinformatics.org/eml-2.0.0", "eml://ecoinformatics.org/eml-2.1.0"), count = c(12937, 4054, 700, 106, 52, 4, 4), already_supported_by_metajam = c("Y", "N", "Y", "IDK", "IDK", "Y", "Y"))

metadata_tbl_LTER <- tibble(repo_name = "urn:node:LTER", metadata_type = c("eml://ecoinformatics.org/eml-2.1.0", "eml://ecoinformatics.org/eml-2.1.1", "eml://ecoinformatics.org/eml-2.0.1", "eml://ecoinformatics.org/eml-2.0.0", "https://eml.ecoinformatics.org/eml-2.2.0"), count = c(48795, 23573, 6450, 916, 691), already_supported_by_metajam = "Y")

metadata_tbl_NCEI <- tibble(repo_name = "urn:node:NCEI", metadata_type = "http://www.isotc211.org/2005/gmd-noaa", count = 50967, already_supported_by_metajam = "N")

metadata_tbl_ARM <- tibble(repo_name = "urn:node:ARM", metadata_type = "http://www.isotc211.org/2005/gmd", count = 12983, already_supported_by_metajam = "N")

metadata_tbl_IEDA_MGDL <- tibble(repo_name = "urn:node:IEDA_MGDL", metadata_type = "http://www.isotc211.org/2005/gmd", count = 9733, already_supported_by_metajam = "N")

metadata_tbl_GRIIDC <- tibble(repo_name = "urn:node:GRIIDC", metadata_type = "http://www.isotc211.org/2005/gmd-noaa", count = 8581, already_supported_by_metajam = "N")

metadata_tbl_NRDC <- tibble(repo_name = "urn:node:NRDC", metadata_type = "http://www.isotc211.org/2005/gmd", count = 2226, already_supported_by_metajam = "N")

metadata_tbl_R2R <- tibble(repo_name = "urn:node:R2R", metadata_type = "http://www.isotc211.org/2005/gmd-noaa", count = 1787, already_supported_by_metajam = "N")

metadata_tbl_IEDA_EARTHCHEM <- tibble(repo_name = "urn:node:IEDA_EARTHCHEM", metadata_type = "http://www.isotc211.org/2005/gmd", count = 888, already_supported_by_metajam = "N")

metadata_tbl_IEDA_USAP <- tibble(repo_name = "urn:node:IEDA_USAP", metadata_type = "http://www.isotc211.org/2005/gmd", count = 695, already_supported_by_metajam = "N")

metadata_tbl_RW <- tibble(repo_name = "urn:node:RW", metadata_type = "http://www.isotc211.org/2005/gmd", count = 353, already_supported_by_metajam = "N")

metadata_tbl_NKW <- tibble(repo_name = "urn:node:NKN", metadata_type = "http://www.isotc211.org/2005/gmd-noaa", count = 9, already_supported_by_metajam = "N")

tbl1 <- merge(metadata_tbl_RW, metadata_tbl_NKW, all =  TRUE)

tbl2 <- merge(metadata_tbl_IEDA_EARTHCHEM, metadata_tbl_IEDA_USAP, all = TRUE)

tbl3 <- merge(metadata_tbl_NRDC, metadata_tbl_R2R, all = TRUE)

tbl4 <- merge( metadata_tbl_IEDA_MGDL, metadata_tbl_GRIIDC, all = TRUE)

tbl5 <- merge(metadata_tbl_NCEI, metadata_tbl_ARM, all = TRUE)

tbl6 <- merge(metadata_tbl_ARCTIC, metadata_tbl_LTER, all = TRUE)

tbl7 <- merge(metadata_tbl_KNB, metadata_tbl_EDI, all = TRUE)

tbl_1 <- merge(tbl1, tbl2, all = TRUE)

tbl_2 <- merge(tbl3, tbl4, all = TRUE)

tbl_3 <- merge(tbl5, tbl6, all = TRUE)

tbl_4 <- merge(tbl7, tbl_1, all = TRUE)

tbl_5 <- merge(tbl_4, tbl_2, all = TRUE)

total_tbl <- merge(tbl_5, tbl_3, all = TRUE)



```

```{r}


already_suported_by_metajam <- total_tbl %>% filter(already_supported_by_metajam == "Y")

already_suported_by_metajam$count <- as.numeric(already_suported_by_metajam$count)

sum(already_suported_by_metajam$count)

new_mns <- unique(not_already_suported_by_metajam$repo_name)

new_mns

```

